development:
    TWITTER_KEY: fVmohsS3LBUSZbG5ciweHA
    TWITTER_SECRET: eaQFzHQMQiJo91FpqAer4G5rkpGuggGRfQUPLfaNx5s

    SOUNDCLOUD_KEY: 84ea89f409433e5adcb2da9ee0449549
    SOUNDCLOUD_SECRET: TZmM0XbY5NCfNBwM1Qq5zV0KAP3SZDyex9WqXOsDGE

production:
    TWITTER_KEY: fVmohsS3LBUSZbG5ciweHA
    TWITTER_SECRET: eaQFzHQMQiJo91FpqAer4G5rkpGuggGRfQUPLfaNx5s

    SOUNDCLOUD_KEY: DeDNYH72GVOkmSU6gBtIDA
    SOUNDCLOUD_SECRET: TZmM0XbY5NCfNBwM1Qq5zV0KAP3SZDyex9WqXOsDGE